# Generated by Django 5.2.6 on 2025-10-01 16:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('name_course', models.CharField(max_length=255, unique=True)),
                ('course_img', models.ImageField(blank=True, null=True, upload_to='courses/images/')),
                ('start_course', models.DateTimeField()),
                ('groups', models.ManyToManyField(blank=True, related_name='courses', to='groups.group')),
                ('instructor', models.ForeignKey(blank=True, limit_choices_to={'roles__name': 'INSTRUCTOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_taught', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'course',
            },
        ),
    ]
