# Generated by Django 5.2.6 on 2025-10-01 16:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('group_name', models.CharField(max_length=255, unique=True)),
                ('group_image', models.ImageField(blank=True, null=True, upload_to='groups/images/')),
                ('start_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'groups',
            },
        ),
    ]
